version: "3.8"
services:
  ubuntu1:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: ubuntu-server1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
    restart: always
    ports:
      - 8080:80